language: nix

# Do not spam me with build status emails.
notifications:
  email: false

install:
  # Make the pinned build environment available on the PATH.
  - export PATH=$(nix-build --no-out-link)/bin:$PATH

script:
  - cargo build
  - cargo test
  - gradle build --project-dir app3
  - mkdocs build

cache:
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.rustup/
    - target
    - app/.psc-package

before_cache:
  - rm -fr "$TRAVIS_HOME/.cargo/registry/src"
