language: nix

# Do not spam me with build status emails.
notifications:
  email: false

before_install:
  # Make the pinned build environment available on the PATH.
  - export PATH=$(nix-build --no-out-link)/bin:$PATH

install:
  # Trigger Rustup to download and install the Rust toolchain.
  - cargo --version

script:
  - cargo build
  - cargo test
  - make -C app
  - mkdocs build

cache:
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.rustup/
    - target
    - app/.psc-package

before_cache:
  - rm -fr "$TRAVIS_HOME/.cargo/registry/src"
