[package]
name = "mindec"
version = "0.0.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]

[dependencies]
# claxon              = "0.4"
claxon                = { path = "../claxon" }
crossbeam             = "0.3"
futures               = "0.1"
hyper                 = "0.11"
serde_json            = "1.0"
unicode-normalization = "0.1.5"
walkdir               = "1.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "main"
harness = false
