[package]
name = "mindec"
version = "0.0.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]

[dependencies]
crossbeam             = "0.7"
futures               = "0.1"
hyper                 = "0.11"
libc                  = "0.2"
serde_json            = "1.0"
unicode-normalization = "0.1.5"
walkdir               = "2.2"

[dependencies.claxon]
git = "https://github.com/ruuda/claxon"
rev = "f3cd5ddaf7ffd56edfa4a218a924a776d4792bdd"

[dev-dependencies]
criterion = "0.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bench]]
name = "main"
harness = false
