site_name: Musium
repo_url: https://github.com/ruuda/musium
strict: true
theme:
  name: null
  custom_dir: docs/theme
nav:
  - Overview: index.md
  - User Guide:
    - Building: building.md
    - Tagging: tagging.md
  - API Reference: api.md
  - Internals:
    - Search: search.md
    - Performance: performance.md
    - Thumbnails: thumbnails.md
